### ISSUE TITLE
mintsources: Adding certain PPAs causes mintsources to not launch

### ISSUE THREAD

**Issue by villamorrd** [linuxmint/mint22-beta#29]
On a fresh install of Mint 22 Cinnamon, if you add a PPA like [LibreOffice Fresh](https://launchpad.net/~libreoffice/+archive/ubuntu/ppa), mintsources does not launch at all.

### Steps to Reproduce
1. Add the PPA with `sudo add-apt-repository ppa:libreoffice/ppa`
2. Run mintsources

Running mintsources from terminal returns this output:
![Screenshot_20240702_001549](https://github.com/linuxmint/mint22-beta/assets/122612351/86774569-ddae-43b5-9d99-edadd9d1a3b0)

**Comment by haggen88** [comment]
I confirm the bug, in my case I tried to install a ppa {Proprietary GPU Drivers} and mintsources does not respond when launched from the menu or system configuration.

ppa:   ppa:graphics-drivers/ppa  
https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa 


mint@mint:~$ mintsources
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1896, in <module>
    Application(os_codename).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 893, in __init__
    self.read_source_lists()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1024, in read_source_lists
    source = Source(self, repo)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 408, in __init__
    self.ppa_owner, self.ppa_name = self.name.split("/")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)

**Comment by scoson** [comment]
Same.. I successfully added QMMP ppa and sources won't launch for me.

`Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1896, in <module>
    Application(os_codename).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 893, in __init__
    self.read_source_lists()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1024, in read_source_lists
    source = Source(self, repo)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 408, in __init__
    self.ppa_owner, self.ppa_name = self.name.split("/")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1)`

**Comment by kneekoo** [comment]
Same problem for me, with these two PPAs:
```
ppa:libreoffice/ppa
ppa:minetestdevs/stable
```

Additionally, on refresh, Mint Update complains about the two PPAs using a weak algorithm (rsa1024).

**Comment by MaravicMarko** [comment]
Same for me:

> marko@MintProBook:~$ mintsources
Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1896, in <module>
    Application(os_codename).run()
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 893, in __init__
    self.read_source_lists()
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 1024, in read_source_lists
    source = Source(self, repo)
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/linuxmint/mintSources/mintSources.py", line 408, in __init__
    self.ppa_owner, self.ppa_name = self.name.split("/")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 1) 
> 
Not posible to open Software Sources from Update Manager or from System Settings. I get elevation prompt, not nothing happens after I put password.

As for others, Mint update is complaning about PPAs for LibreOffice Fresh and Grub Customizer using weak algorithm.
Those two are only PPAs added.

Fresh install of 22 Beta. Of additional programs, I only insatlled Nala, Vivaldi and Grub Customizer.

**Comment by clefebvre** [comment]
Crash fixed on github.

I still need to fix the key mechanism, it looks like it changed in Launchad.

**Comment by clefebvre** [comment]
Ok, regarding the signature issue, it's upstream on Launchpad and being addressed: https://answers.launchpad.net/launchpad/+question/809194.
